@startuml tramway

class WorldView {
  segmentQueues: List
  
  redraw(): void
}
WorldView -- WorldModel
WorldView *-- "10" TrafficLight

class WorldModel {
}
WorldModel *-- "6" Tram
WorldModel *-- "*" Car
WorldModel *-- "1" BridgeArbiter
WorldModel *-- "1" IntersectionArbiter

abstract class TrafficArbiter {
  p(Semaphore x): void
  v(Semaphore x): void
  getPermit(TrafficDirection dir): void
  releasePermit(TrafficDirection dir): void
}

class BridgeArbiter {
}
BridgeArbiter --|> TrafficArbiter

class IntersectionArbiter {
}
IntersectionArbiter --|> TrafficArbiter

abstract class Vehicle {
  dir: TrafficDirection
  canAdvance: Semaphore

  advance(): void
  enter(): void
  leave(): void
}
class Tram {
}
class Car {
}
Tram --|> Vehicle
Car --|> Vehicle
Vehicle -- TrafficArbiter

Vehicle --|> Thread

class TrafficLight {
  setColor(String c): void
  getColor(): String
}

enum TrafficColor {
  GREEN
  RED
  YELLOW
}

enum TrafficDirection {
  NORTH
  SOUTH
  EAST
  WEST
}

@enduml
